# Generated by Django 2.1.3 on 2019-01-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciscoapp', '0006_qotw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='qotw',
        ),
    ]
