# Generated by Django 2.1.3 on 2019-01-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciscoapp', '0008_qotw'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.CharField(db_column='username', default='Shreyas', max_length=100),
        ),
    ]
