# Generated by Django 2.1.3 on 2019-01-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciscoapp', '0009_question_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='username',
            field=models.CharField(db_column='username', max_length=100),
        ),
    ]
